spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.google.books.key=${GOOGLE_BOOKS_NET}

fire.base.path=${FIRE-BASE-API-KEY}

spring.datasource.hikari.initialization-fail-timeout=60000

spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.max-lifetime=1800000

